export enum Role {
  ADMIN = "ADMIN",
  CHEMIST = "CHEMIST",
  SHIFT_CHEMIST = "SHIFT_CHEMIST",
  ASSISTING_MANAGER = "ASSISTING_MANAGER",
  HEAD_MANAGER = "HEAD_MANAGER",
  ENGINEER = "ENGINEER",
  DISPATCH = "DISPATCH",
}
